name: PingStaticman

on:
  schedule:
    - cron:  '1,11,21,31,41,51 * * * *'
  workflow_dispatch:

jobs:
  ping_staticman:
    runs-on: ubuntu-latest

    steps:
      - name: Ping
        continue-on-error: true
        run: 'wget --timeout=30 -q -O - https://post.electbitcoin.org | grep "Hello from Staticman version 3.0.0!"'
        
      - name: Ping Again
        run: 'sleep 30 && wget --timeout=30 -q -O - https://post.electbitcoin.org | grep "Hello from Staticman version 3.0.0!"'
