name: PingStaticman

on:
  schedule:
    - cron:  '1,11,21,31,41,51 * * * *'
  workflow_dispatch:

jobs:
  ping_staticman:
    runs-on: ubuntu-latest

    steps:
      - name: Ping
        run: |
          'wget --timeout=30 --verbose -O ./output.txt https://post.electbitcoin.org'
          'cat output.txt'
          'grep "Hello from Staticman version 3.0.0!" output.txt'
          'rm output.txt'
